### ISSUE TITLE
Can not get this to work. "string index out of range"

### ISSUE THREAD

**Issue by GamingDaveUk** [AIFSH/ComfyUI-3d-photo-inpainting#8]
This is EXACTLY what i was looking for on paper, but it refuses to work. 

[3dzoom.json](https://github.com/user-attachments/files/17624373/3dzoom.json)
![image](https://github.com/user-attachments/assets/ba5f8ef9-925a-414b-a444-42b0feb4a4c0)

I created a simplistic workflow. But I get the following error when I run it:

`Traceback (most recent call last):
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3d-photo-inpainting\3dphoto\main.py", line 12, in <module>
    from mesh import write_ply, read_ply, output_3d_photo
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3d-photo-inpainting\3dphoto\mesh.py", line 19, in <module>
    from utils import path_planning, open_small_mask, clean_far_edge, refine_depth_around_edge
ImportError: cannot import name 'path_planning' from 'utils' (D:\AI\ComfyUI_windows_portable\ComfyUI\utils\__init__.py)
Prompt executed in 7.28 seconds
Error handling request
Traceback (most recent call last):
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_protocol.py", line 477, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_app.py", line 559, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\server.py", line 63, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\server.py", line 141, in origin_only_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\server.py", line 75, in cors_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\server.py", line 385, in view_image
    if filename[0] == '/' or '..' in filename:
       ~~~~~~~~^^^
IndexError: string index out of range
`

**Comment by noobtoob4lyfe** [comment]
I get the exact same error.  help please.  Thanks

**Comment by Avin-Mile** [comment]
Same error, still not be fixed.
